name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_opts: [
          "-XX:+PrintFlagsFinal -XX:+UseG1GC",
          "-XX:+UnlockExperimentalVMOptions -XX:+UseStringDeduplication",
          "-XX:+PrintGCDetails ",
          "-XX:+UseG1GC -XX:+PrintGCDetails"
        ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set Maven options
        run: echo "MAVEN_OPTS=${{ matrix.jvm_opts }}" >> $GITHUB_ENV

      - name: Build and Test with Maven
        timeout-minutes: 15
        env:
          MAVEN_OPTS: ${{ matrix.jvm_opts }}
        run: |
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "COVERAGE=$coverage" >> $GITHUB_ENV

      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=24.46
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage is not improved."
            exit 1
          else
            echo "New coverage: $coverage%. Coverage is improved!"
          fi
